//! Theme color tokens shared by GUI panels and reusable widgets.

#[derive(Clone, Copy)]
pub(super) struct Palette {
    pub(super) bg: egui::Color32,
    pub(super) side: egui::Color32,
    pub(super) panel: egui::Color32,
    pub(super) head_fill: egui::Color32,
    pub(super) head_border: egui::Color32,
    pub(super) field: egui::Color32,
    pub(super) border: egui::Color32,
    pub(super) text: egui::Color32,
    pub(super) dim: egui::Color32,
    pub(super) accent: egui::Color32,
    pub(super) hover: egui::Color32,
    pub(super) btn_fill: egui::Color32,
    pub(super) btn_hover: egui::Color32,
    pub(super) btn_text: egui::Color32,
    pub(super) btn_border: egui::Color32,
    pub(super) user_bubble: egui::Color32,
    pub(super) user_text: egui::Color32,
    pub(super) ai_bubble: egui::Color32,
    /// 工具执行气泡底色（当前消息流已改用 render_work_batch 配色，暂保留供后续复用）。
    #[allow(dead_code)]
    pub(super) tool_bubble: egui::Color32,
    pub(super) err_bubble: egui::Color32,
    pub(super) err_text: egui::Color32,
    pub(super) warn: egui::Color32,
    pub(super) banner_ok: egui::Color32,
    pub(super) banner_warn: egui::Color32,
    pub(super) diff_add_bg: egui::Color32,
    pub(super) diff_del_bg: egui::Color32,
    pub(super) diff_hunk_bg: egui::Color32,
    pub(super) diff_sign_add: egui::Color32,
    pub(super) diff_sign_del: egui::Color32,
}

pub(super) fn palette(dark: bool) -> Palette {
    use egui::Color32 as C;
    if dark {
        Palette {
            bg: C::from_rgb(0x0e, 0x13, 0x1a),
            side: C::from_rgb(0x12, 0x18, 0x22),
            panel: C::from_rgb(0x15, 0x1c, 0x28),
            head_fill: C::from_rgb(0x13, 0x22, 0x2b),
            head_border: C::from_rgb(0x2d, 0x5e, 0x52),
            field: C::from_rgb(0x16, 0x1f, 0x2b),
            border: C::from_rgb(0x27, 0x33, 0x44),
            text: C::from_rgb(0xeb, 0xf1, 0xf7),
            dim: C::from_rgb(0x8f, 0xa3, 0xba),
            accent: C::from_rgb(0x4e, 0xd4, 0xa9),
            hover: C::from_rgb(0x1c, 0x28, 0x38),
            btn_fill: C::from_rgb(0x1e, 0x3f, 0x36),
            btn_hover: C::from_rgb(0x27, 0x55, 0x48),
            btn_text: C::from_rgb(0x95, 0xf2, 0xd4),
            btn_border: C::from_rgb(0x2d, 0x5e, 0x52),
            user_bubble: C::from_rgb(0x24, 0x36, 0x4f),
            user_text: C::from_rgb(0xf0, 0xf6, 0xfc),
            ai_bubble: C::from_rgb(0x18, 0x23, 0x32),
            tool_bubble: C::from_rgb(0x14, 0x1d, 0x28),
            err_bubble: C::from_rgb(0x38, 0x17, 0x21),
            err_text: C::from_rgb(0xff, 0xa6, 0xb4),
            warn: C::from_rgb(0xff, 0xba, 0x6e),
            banner_ok: C::from_rgb(0x18, 0x38, 0x2e),
            banner_warn: C::from_rgb(0x38, 0x2c, 0x14),
            diff_add_bg: C::from_rgb(0x19, 0x3b, 0x29),
            diff_del_bg: C::from_rgb(0x4d, 0x1f, 0x24),
            diff_hunk_bg: C::from_rgb(0x1a, 0x2b, 0x42),
            diff_sign_add: C::from_rgb(0x4a, 0xc9, 0x8a),
            diff_sign_del: C::from_rgb(0xff, 0x8a, 0x95),
        }
    } else {
        Palette {
            bg: C::WHITE,
            side: C::WHITE,
            panel: C::WHITE,
            head_fill: C::from_rgb(0xe9, 0xf5, 0xef),
            head_border: C::from_rgb(0xa9, 0xd8, 0xc6),
            field: C::from_rgb(0xf2, 0xf5, 0xf9),
            border: C::from_rgb(0xd7, 0xdf, 0xe8),
            text: C::from_rgb(0x1a, 0x24, 0x30),
            dim: C::from_rgb(0x61, 0x70, 0x82),
            accent: C::from_rgb(0x0e, 0x8a, 0x67),
            hover: C::from_rgb(0xe8, 0xef, 0xf7),
            btn_fill: C::from_rgb(0xe2, 0xf4, 0xed),
            btn_hover: C::from_rgb(0xd0, 0xeb, 0xdf),
            btn_text: C::from_rgb(0x0c, 0x7a, 0x5b),
            btn_border: C::from_rgb(0xa9, 0xd8, 0xc6),
            user_bubble: C::from_rgb(0xe3, 0xeb, 0xf5),
            user_text: C::from_rgb(0x1a, 0x24, 0x30),
            ai_bubble: C::from_rgb(0xf0, 0xf3, 0xf8),
            tool_bubble: C::from_rgb(0xf5, 0xf7, 0xfa),
            err_bubble: C::from_rgb(0xfb, 0xe5, 0xe9),
            err_text: C::from_rgb(0xb3, 0x26, 0x3c),
            warn: C::from_rgb(0xc2, 0x6a, 0x00),
            banner_ok: C::from_rgb(0xe2, 0xf4, 0xed),
            banner_warn: C::from_rgb(0xfd, 0xf1, 0xdc),
            diff_add_bg: C::from_rgb(0xe6, 0xff, 0xec),
            diff_del_bg: C::from_rgb(0xff, 0xeb, 0xe9),
            diff_hunk_bg: C::from_rgb(0xf0, 0xf6, 0xff),
            diff_sign_add: C::from_rgb(0x0a, 0x84, 0x38),
            diff_sign_del: C::from_rgb(0xcf, 0x22, 0x2e),
        }
    }
}
